### ISSUE TITLE
Stopped working on Win7 after latest commit.

### ISSUE THREAD

**Issue by xska2** [SublimeLinter/SublimeLinter-shellcheck#10]
Used to work fine previously with shellcheck compiled using windows Haskell install. After the latest change it bails with this:

```

reloading plugin SublimeLinter-shellcheck.linter
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "linter in C:\Users\user\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter-shellcheck.sublime-package", line 28, in <module>
  File "linter in C:\Users\user\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter-shellcheck.sublime-package", line 38, in Shellcheck
OSError: Either the current system is not 64-bit, or WSL is not enabled. See the README file.
```

**Comment by kaste** [comment]
Oh. 🤐

So, you have a native windows binary.

We thought there isn't any, so you MUST use wsl on Windows.

**Comment by xska2** [comment]
Yep. It's a bit involved to compile one, but definitely possible (following instructions on https://github.com/koalaman/shellcheck#compiling-from-source).

**Comment by kaste** [comment]
First aid, we just don't throw. 

That means, if you have `wsl` it is the preferred method.

**Comment by kaste** [comment]
Released. Coming to you in the next hour.

**Comment by xska2** [comment]
Brilliant, just tested it - looks good. Thanks.

**Comment by koumdros** [comment]
so what do we do if we have to work on Windows 7 where there is no WSL?

can you point us to the last version that worked? been using this with the linked binary from shellcheck repo for some time without problems...
"https://storage.googleapis.com/shellcheck/shellcheck-latest.zip"

**Comment by koumdros** [comment]
> If you don't have wsl then it doesn't use it? <
hm, I don't really get what you;re saying here.
No, there is no WSL in W7 , and yep, since.. 2-3 months, not really sure when the problem started, spellcheck fails.

**Comment by kaste** [comment]
@koumdros Can you be more specific, please. Maybe enable debug mode, look at the console output, and in case post it.
